name: CI

on:
  schedule:
    - cron:  '0 7 * * *' # daily, 7am

  push:
    branches:
      - main
      - 'v*' # prior release branches (e.g. `v0.30.x` branch)
    tags:
      - 'v*'
  pull_request:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v1
      - uses: volta-cli/action@v1

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-cache
          restore-keys: |
            yarn-cache
      - name: yarn --frozen-lockfile
        run: yarn --frozen-lockfile

      - name: lint
        run: yarn lint

      - name: upload-built-files
        uses: actions/upload-artifact@v2
        with:
          name: ubuntu-files
          path: "**"

      - id: set-matrix
        run: echo "::set-output name=matrix::$(yarn matrix)"

  test:
    needs: ["setup"]
    name: ${{ matrix.name }}
    runs-on: '${{ matrix.os }}-latest'
    timeout-minutes: 15

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v1
      - uses: volta-cli/action@v1
      - name: download-built-files
        uses:  actions/download-artifact@v2
        with:
          name: ubuntu-files
      - name: test
        run: yarn test
